// Generated by '@import-meta-env/typescript'

interface ImportMetaEnv {
  readonly SUPABASE_DB_FUNCTION_URL: string;
  readonly SUPABASE_ANON_KEY: string;
  readonly SUPABASE_PUBLIC_URL: string;
}

interface ImportMeta {
  readonly env: ImportMetaEnv;
}
